version: '3.8'

services:
  app:
    image: golang:1.20
    volumes:
      - .:/go/src/app/
    working_dir: /go/src/app/
    command: go run app.go
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=grow
      - DB_PASSWORD=grow
      - DB_NAME=growalert
      - VM_URL=http://victoriametrics:8428
    depends_on:
      - db
      - victoriametrics

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=grow
      - POSTGRES_PASSWORD=grow
      - POSTGRES_DB=growalert
    volumes:
      - postgres_data:/var/lib/postgresql/data

  victoriametrics:
    image: victoriametrics/victoria-metrics
    command:
      - '-storageDataPath=/victoria-metrics-data'
      - '-retentionPeriod=12'
    ports:
      - "8428:8428"
    volumes:
      - victoria_metrics_data:/victoria-metrics-data

volumes:
  postgres_data:
  victoria_metrics_data:

